#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 <<-EOSQL
    CREATE ROLE DB_READER;
    CREATE ROLE DB_WRITER;

    CREATE ROLE service WITH LOGIN PASSWORD '${DB_SERVICE_PASSWORD}';
    CREATE ROLE liquibase WITH LOGIN PASSWORD '${DB_LIQUIBASE_PASSWORD}';

    GRANT DB_WRITER to service;
    
    GRANT USAGE ON SCHEMA public TO DB_READER;
    GRANT USAGE ON SCHEMA public TO DB_WRITER;
    GRANT ALL ON SCHEMA public TO liquibase;

    ALTER DEFAULT PRIVILEGES FOR ROLE liquibase IN SCHEMA public GRANT SELECT ON TABLES TO DB_READER;
    ALTER DEFAULT PRIVILEGES FOR ROLE liquibase IN SCHEMA public GRANT SELECT ON SEQUENCES TO DB_READER;
    
    ALTER DEFAULT PRIVILEGES FOR ROLE liquibase IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO DB_WRITER;
    ALTER DEFAULT PRIVILEGES FOR ROLE liquibase IN SCHEMA public GRANT ALL ON SEQUENCES TO DB_WRITER;
EOSQL